# Generated by Django 3.1.1 on 2020-09-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_word', models.CharField(max_length=300)),
                ('today_mean', models.CharField(max_length=300)),
            ],
        ),
    ]
