# Generated by Django 3.1.1 on 2020-10-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201008_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voca',
            name='user',
        ),
    ]
