# Generated by Django 3.1.2 on 2020-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_voca_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_test_point',
            field=models.IntegerField(default=0),
        ),
    ]
