# Generated by Django 3.1.3 on 2020-11-15 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='할일제목')),
                ('description', models.TextField(max_length=200, verbose_name='할일세부사항')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='생성날짜')),
                ('date_deadline', models.DateField(verbose_name='데드라인')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
